[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[context.production]
environment = { NODE_VERSION = "16" }

[dev]
  framework = "astro"
  targetPort = 4321 # 👈 puerto donde corre Astro en dev
  port = 8888       # 👈 puerto que usará Netlify Dev
  command = "npm run dev"
  publish = "dist"
  functions = "netlify/functions"

# 👇 PROXY: cuando pidas /api o /.netlify/functions en dev
[[redirects]]
  from = "/.netlify/functions/*"
  to = "http://localhost:9999/.netlify/functions/:splat"
  status = 200
  force = true


