[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[context.production]
environment = { NODE_VERSION = "16" }

[dev]
  framework = "astro"
  targetPort = 4321 # 👈 puerto donde corre Astro en dev
  port = 8888       # 👈 puerto que usará Netlify Dev
  command = "npm run dev"
  publish = "dist"
  functions = "netlify/functions"

# 👇 ESTA REGLA SOLO SE USA LOCALMENTE
# Si quieres mantenerla para desarrollo, cámbiala a esto:
[context.dev]
  [[redirects]]
    from = "/api/*"
    to = "http://localhost:9999/.netlify/functions/:splat"
    status = 200
    force = true



